package railwayman;


import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet; 
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.CallableStatement;
/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MAHE
 */
public class SignUp extends javax.swing.JFrame {
 CallableStatement cs=null;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        
        initComponents();
    jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setText("Enter User id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 397, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel2.setText("Enter First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 47, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setText("Enter Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setText("Enter Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 121, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel5.setText("Enter age in number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 147, -1, 23));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel6.setText("Enter Adhaar number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 176, -1, 23));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel9.setText("Enter city:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 288, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel10.setText("Enter pincode:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 344, -1, 22));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel11.setText("Enter Password:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 435, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel12.setText("Select Your Preferred Security Question:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 504, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel13.setText("Enter the Answer for Security Question:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 531, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 429, -1, -1));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 145, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel14.setText("Confirm Password:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 466, -1, -1));

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jPasswordField2.setText("jPasswordField2");
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 460, -1, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 553, -1, -1));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 145, -1));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 148, 111, -1));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 177, 111, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 282, 111, -1));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 345, 111, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 131, -1));

        jTextField11.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 391, 111, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Favorite Flower?", "Name of your pet?", "Favorite Animal?", "Favorite colour?" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        jButton2.setText("Confirm Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String com= (String)jComboBox1.getSelectedItem();
   JOptionPane.showMessageDialog(null, "Enter your answer");
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
         int age = Integer.parseInt(jTextField3.getText());
         if(age<18)
         { JOptionPane.showMessageDialog(null, "Invalid Age, please enter age above 18");    
         jTextField3.setText(null);
         }
         else if((age>0) && (age<107))
         { JOptionPane.showMessageDialog(null, "Your Age is: " +age);}
         else
         {JOptionPane.showMessageDialog(null, "Invalid Age");
            jTextField3.setText(null);
         }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
   String first_name = jTextField1.getText();
    String last_name = jTextField2.getText();
    String gender = (String)jComboBox2.getSelectedItem();
    String age = jTextField3.getText();
    int v= Integer.parseInt(age);
    String aadhar_no = jTextField4.getText();
    String city = jTextField7.getText();
    String pincode = jTextField9.getText();
    String user_id = jTextField11.getText();
    int u=Integer.parseInt(user_id);
     String password = jPasswordField1.getText();
     String security_ques = (String)jComboBox1.getSelectedItem();
     String security_ans  = jTextField10.getText();
     String pass2 = jPasswordField2.getText();
     
    if(!security_ans.isEmpty()&& security_ans!= null){
     if(pass2.contentEquals(password)&& password!=null && !password.isEmpty()){
         //if(!security_ans.contentEquals(null))
    //  String user2 = "insert into user2 values ('"+user_id+"','"+password+"','"+first_name+"','"+last_name+"','"+gender+"','"+age+"','"+aadhar_no+"','"+city+"','"+pincode+"','"+security_ques+"','"+security_ans+"')";
   // System.out.println(user2);
    //else{ jPasswordField1.setText(null);
       //   String user2 = "insert into user2 values ('"+user_id+"','"+password+"','"+first_name+"','"+last_name+"','"+gender+"','"+age+"','"+aadhar_no+"','"+city+"','"+pincode+"','"+security_ques+"','"+security_ans+"')";   }
     

    try {
        
        
        
        Class.forName("oracle.jdbc.driver.OracleDriver");

//step2 create  the connection object  
            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "shivi");

//step3 create the statement object  
            Statement stmt = con.createStatement();
        
            
       //  stmt.executeUpdate(user2);
      CallableStatement cs = con.prepareCall("{call insert1(?, ?, ?, ?, ?, ? ,?, ?, ?,?,?)}");
        
 
            cs.setInt(1, u);
            cs.setString(2, first_name);
           cs.setString(3, last_name);
           cs.setString(4, aadhar_no);
           cs.setString(5, gender);
           cs.setInt(6, v);
           cs.setString(7, city);
           cs.setString(8, pincode);
           cs.setString(9, password);
           cs.setString(10, security_ques);
           cs.setString(11, security_ans);
           cs.execute();
            cs.close();
 
        JOptionPane.showMessageDialog(null, "Saved");
        new Menu(Integer.parseInt(user_id)).setVisible(true);
        this.setVisible(false);
    } catch (ClassNotFoundException | SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Please enter all details or another username id");
        e.printStackTrace();
    
     }}
     else
         JOptionPane.showMessageDialog(null, "Enter Password Properly");
        
      /*  if (jTextField1.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter First Name");
            } 
       else if (jTextField2.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter Last Name");
            }
        else if (jTextField3.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter Age");
            }
        else if (jTextField4.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter Adhaar number");
            }
     else if (jPasswordField2.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter Adhaar number");
            }
     
        else if (jTextField8.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter city");}
        else if (jTextField9.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter pincode");}
        else if (jTextField10.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter Answer");}
        else if (jTextField11.getText()==null)
            {JOptionPane.showMessageDialog(null, "Please enter User Id");}
       // TODO add your handling code here:*/
      /*  else
        {  new Login().setVisible(true);
        this.setVisible(false);
        }
        */
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
else {
    JOptionPane.showMessageDialog(null,"Please Enter security answer or password properly");
    this.setVisible(false);
    Login l=new Login();
    l.setVisible(true);
}
    } 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jPasswordField2.getText()!=null && !jPasswordField2.getText().isEmpty()){
            if(jPasswordField1.getText()!=null && !jPasswordField1.getText().isEmpty()){
         if (jPasswordField1.getText().equals(jPasswordField2.getText())) {
            JOptionPane.showMessageDialog(null, "Username and password set");
            Login.uid = jTextField1.getText();
            Login.pwd = jPasswordField1.getText();
          jButton1.setVisible(true);}}}
         else{ JOptionPane.showMessageDialog(null, "Enter the right password");
             jPasswordField1.setText(null);
             jButton1.setVisible(false);
         
         };
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
